"""index stock_movements.created_at

Revision ID: 64d1d6436d2a
Revises: 6b28e60f8bb6
Create Date: 2026-07-30 23:59:28.159071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d1d6436d2a'
down_revision: Union[str, None] = '6b28e60f8bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    # ### end Alembic commands ###
