"""add_orders_order_items_fix_stock_movements

Revision ID: 8e706f6828f0
Revises: c82b23f0baf1
Create Date: 2026-05-12 10:48:18.293079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e706f6828f0'
down_revision: Union[str, None] = 'c82b23f0baf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FULFILLED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
        # --- Fix stock_movements ---

    # Step 1: add product_sku as nullable first (existing rows would fail NOT NULL)
    op.add_column('stock_movements', sa.Column('product_sku', sa.String(length=100), nullable=True))

    # Step 2: backfill product_sku from the products table for all existing rows
    op.execute("""
        UPDATE stock_movements sm
        SET product_sku = p.sku
        FROM products p
        WHERE sm.product_id = p.id
    """)

    # Step 3: now safe to enforce NOT NULL — every existing row has a value
    op.alter_column('stock_movements', 'product_sku', nullable=False)

    # Step 4: make product_id nullable (was NOT NULL before)
    op.alter_column('stock_movements', 'product_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # Step 5: drop old CASCADE constraint and replace with SET NULL
    op.drop_constraint('stock_movements_product_id_fkey', 'stock_movements', type_='foreignkey')
    op.create_foreign_key(None, 'stock_movements', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Fixed — explicit name, Pylance happy, same behaviour
    op.drop_constraint('stock_movements_product_id_fkey1', 'stock_movements', type_='foreignkey')   
    op.create_foreign_key('stock_movements_product_id_fkey1', 'stock_movements', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('stock_movements', 'product_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('stock_movements', 'product_sku')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
